default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: react_rails_static_test

production:
  <<: *default
  database: react_rails_static_production
  username: react_rails_static
  password: <%= ENV['REACT_RAILS_STATIC_DATABASE_PASSWORD'] %>
